import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// TailwindのスタイルやリセットCSSのために必要
import "./globals.css";
import Header from '@/components/common/Header';
import { AuthProvider } from '@/context/AuthContext';

// Google Fonts 経由でWebフォントを読み込んでいる
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ページタイトルやmeta情報として使われます
export const metadata: Metadata = {
  title: '今日のダッシュボード',
  description: "Generated by create next app",
};

// すべてのページ共通レイアウトを定義、フォントをCSS変数で使えるようにしている
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-gray-800`}
      >
        <AuthProvider>
          <Header />
          <main className="flex flex-col items-center justify-center w-full">
              {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}